site_name: ANGELIX
site_url: https://angelix-sys.github.io/
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
